import React, { useState } from 'react';
import { ProductQueryUnderstanding } from '../types/product';
import { BrainCircuit, Search, ChevronDown, ChevronUp, AlertCircle, CheckCircle2 } from 'lucide-react';

interface QueryUnderstandingCardProps {
  understanding?: ProductQueryUnderstanding;
}

export const QueryUnderstandingCard: React.FC<QueryUnderstandingCardProps> = ({
  understanding,
}) => {
  const [isExpanded, setIsExpanded] = useState<boolean>(true);

  if (!understanding) return null;

  const confidencePct = Math.round((understanding.confidence || 0.8) * 100);

  return (
    <div className="bg-white rounded-2xl border border-zinc-200 p-6 shadow-sm overflow-hidden">
      {/* Header with Toggle */}
      <div className="flex items-center justify-between gap-4 pb-4 border-b border-zinc-100">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-xl bg-zinc-900 text-white">
            <BrainCircuit className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm sm:text-base font-bold text-zinc-950 flex items-center gap-2">
              <span>AI Query Interpretation & Search Plan</span>
              <span className="text-[11px] font-semibold px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200">
                {confidencePct}% Intent Confidence
              </span>
            </h3>
            <p className="text-xs text-zinc-500">
              Normalized parameters and targeted supplier queries generated by the understanding layer.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={() => setIsExpanded(!isExpanded)}
          className="p-1.5 rounded-lg text-zinc-500 hover:text-zinc-800 hover:bg-zinc-100 transition-colors"
          aria-label={isExpanded ? 'Collapse plan' : 'Expand plan'}
        >
          {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </button>
      </div>

      {isExpanded && (
        <div className="mt-5 space-y-5 text-xs sm:text-sm">
          {/* Attributes Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-zinc-50/70 p-3.5 rounded-xl border border-zinc-200/80">
            <div>
              <span className="text-[11px] font-semibold uppercase tracking-wider text-zinc-400 block mb-1">
                Category
              </span>
              <span className="font-medium text-zinc-900">{understanding.category}</span>
            </div>
            <div>
              <span className="text-[11px] font-semibold uppercase tracking-wider text-zinc-400 block mb-1">
                Material
              </span>
              <span className="font-medium text-zinc-900">{understanding.material || 'Standard Composite'}</span>
            </div>
            <div>
              <span className="text-[11px] font-semibold uppercase tracking-wider text-zinc-400 block mb-1">
                Brand
              </span>
              <span className="font-medium text-zinc-900">{understanding.brand || 'Unspecified'}</span>
            </div>
            <div>
              <span className="text-[11px] font-semibold uppercase tracking-wider text-zinc-400 block mb-1">
                Model / Code
              </span>
              <span className="font-medium text-zinc-900">{understanding.model || 'Standard Trade'}</span>
            </div>
          </div>

          {/* Identified Specs from Query */}
          {understanding.specifications && understanding.specifications.length > 0 && (
            <div>
              <span className="text-xs font-semibold text-zinc-500 uppercase tracking-wider block mb-2">
                Preserved Query Specifications & Dimensions
              </span>
              <div className="flex flex-wrap gap-2">
                {understanding.specifications.map((spec, idx) => (
                  <span
                    key={idx}
                    className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-blue-50 text-blue-800 font-mono text-xs border border-blue-200 font-medium"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5 text-blue-600" />
                    {spec}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Generated Search Queries */}
          {understanding.search_queries && understanding.search_queries.length > 0 && (
            <div>
              <span className="text-xs font-semibold text-zinc-500 uppercase tracking-wider block mb-2">
                Generated Web Research Queries
              </span>
              <div className="space-y-1.5">
                {understanding.search_queries.map((q, idx) => (
                  <div
                    key={idx}
                    className="flex items-center gap-2 p-2 rounded-lg bg-zinc-50 border border-zinc-200 text-zinc-700 font-mono text-xs"
                  >
                    <Search className="w-3.5 h-3.5 text-zinc-400 flex-shrink-0" />
                    <span>"{q}"</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Identified Ambiguities / Uncertainties */}
          {understanding.uncertainties && understanding.uncertainties.length > 0 && (
            <div className="pt-2 border-t border-zinc-150">
              <span className="text-xs font-semibold text-amber-900 uppercase tracking-wider block mb-1.5 flex items-center gap-1">
                <AlertCircle className="w-3.5 h-3.5 text-amber-700" />
                <span>Identified Ambiguities</span>
              </span>
              <ul className="list-disc list-inside space-y-1 text-xs text-zinc-600">
                {understanding.uncertainties.map((u, idx) => (
                  <li key={idx}>{u}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
